name: "account-service"
grpc:
  port: 9090
  enable_health_check: true
logger:
  level: "info"
  encoding: "json"
  disable_stacktrace: false
  environment: "development"
  service_name: "account-service"